sudo: required
services:
  - docker
  
before_install: 
  - docker build -t muzmov/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run muzmov/react-test npm test -- --coverage
  
after_success:
  - docker build -t muzmov/multi-client ./client
  - docker build -t muzmov/multi-worker ./worker
  - docker build -t muzmov/multi-server ./server
  - docker build -t muzmov/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push muzmov/multi-client
  - docker push muzmov/multi-worker
  - docker push muzmov/multi-server
  - docker push muzmov/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-995459693010"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"